In [9]:
%run "! DEFAULT PLOT THINGIES.ipynb"
%run "../! DEFAULT PLOT THINGIES.ipynb"

from __future__ import division

ERROR: File `u'! DEFAULT PLOT THINGIES.ipynb.py'` not found.


<IPython.core.display.Javascript object>

`%matplotlib` prevents importing * from pylab and numpy


Current working directory is now c:\users\deen\dropbox\phd rearrangements\thesis\notebooks\mkbk-links-rechts-correlaties
Populating the interactive namespace from numpy and matplotlib


In [10]:
reverseshear = tables.File(r"E:\PhD rearrangements\auto\reverse_shear\shear_summary_cache.h5").root.data.read()

In [11]:
rN = reverseshear["N"]
Ns = np.unique(rN)
rlP = np.round(np.log10(reverseshear["P"]),2)
lPs = np.unique(rlP)

np.unique(zip(rN, rlP))

array([   -6.,    -3.,    16.,   256.,  1024.])

In [12]:
def getidx(pack):
    # mk bk mx

    if pack["N+_plus"] == 0 and pack["N-_plus"] > 0:
        return 0
    elif pack["N+_plus"] > 0 and pack["N-_plus"] == 0:
        return 1
    else:
        return 2


In [13]:
for N in [256]:
    for lP in [-3]:
        print N, lP
        print "    bk    mk"
        
        data = np.zeros((3,3))

        for revpack in reverseshear[(rN == N) * (rlP == lP)]:
            try:
                fwdpack = summ[(dataN == N) * (datalP == lP) * (summ["num"] == revpack["num"])][0]
            except IndexError:
                pass
            data[getidx(fwdpack), getidx(revpack)] += 1

        Oij = data[:2,:2]
        
        # expected cts
        Eij = np.tile(np.nan, (2,2))
        for i in [0,1]:
            for j in [0,1]:
                Eij[i,j] = np.sum(Oij[i]) * np.sum(Oij[:,j]) / np.sum(Oij)
                
        print Oij
        print Eij
        
        print "chisq = ", np.sum((Oij-Eij)**2 / Oij)
        
        
        
        print ""

256 -3
    bk    mk
[[ 412.  239.]
 [ 198.  129.]]
[[ 406.04294479  244.95705521]
 [ 203.95705521  123.04294479]]
chisq =  0.688925388433

